### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by robotjsorg** [frnsys/hosny#2]
I want to check macOS support (via `brew`). Also `apt-get install redis asyncio` (`brew install redis asyncio`) was missing from the docs.
I also want to check and add `zsh` integration.

Finally, it isn't clear whether we should be using Python 2 or 3.

**Comment by frnsys** [comment]
hey thanks for your interest! It should run with Python 3 and run on Ubuntu. It hasn't been fully-tested in OSX though.

**Comment by robotjsorg** [comment]
Are you on Ubuntu 14 or 16?

**Comment by robotjsorg** [comment]
Current status on macOS using `python3`
redis-server responds with this error when I connect to `http://localhost:5000`

```
3240:M 22 Mar 16:16:29.950 # Possible SECURITY ATTACK detected. It looks like somebody is sending POST or Host: commands to Redis. This is likely due to an attacker attempting to use Cross Protocol Scripting to compromise your Redis instance. Connection aborted.
```

**Comment by frnsys** [comment]
it's been tested on ubuntu 14.04 and 16.04

what port are you running redis on?

**Comment by robotjsorg** [comment]
It randomly started working today on macOS.

The trick was to install everything with `pip3` so that my Python 2.7 installation was not a problem. Also, even though Redis says it is running on Port 6379 and gives the previous error from visiting `localhost:6379`, visiting `localhost:5000` made it work!

Also, `zsh` works just fine instead of `bash`. :)

So I guess it always worked, I was just operating incorrectly.
